# Perfil H2 (apenas para testes rápidos e desenvolvimento offline sem Docker)
spring.datasource.url=jdbc:h2:file:./data/gestao_matriculas;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# H2 Console web em http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Cache em Memória de Altíssimo Desempenho (Caffeine) para desenvolvimento rápido
spring.cache.type=caffeine
